@startuml
object 要求
object 地区大会完走 {
    date: 2017-09-17
}
要求 o-- 地区大会完走
  地区大会完走 o-- 試走会完走
    試走会完走 o-- 簡易コース完走
      簡易コース完走 o-- ライントレース
        ライントレース o-- 倒立制御
          倒立制御 o-- プログラム設計
          倒立制御 o-- 制御周期の確保4ms
          倒立制御 o-- 禁則事項の把握_倒立ライブラリ
          倒立制御 o-- ロボット制御API作成
            ロボット制御API作成 o-- ラインセンサの入出力
            ロボット制御API作成 o-- ジャイロセンサの入出力

            プログラム設計 o-- ロボットのスペック把握
            プログラム設計 o-- OSのスペック把握
            プログラム設計 o-- 設計勉強_セミナー受講
            制御周期の確保4ms o-- ロボットのスペック把握
            制御周期の確保4ms o-- OSのスペック把握
            制御周期の確保4ms o-- 設計勉強_セミナー受講
              ロボットのスペック把握 o-- EV3開発環境構築
              ロボットのスペック把握 o-- Python開発環境構築
              OSのスペック把握 o-- EV3開発環境構築
              OSのスペック把握 o-- Python開発環境構築
    試走会完走 o-- 任意タイミングでのスタート
    試走会完走 o-- 二股ラインのクリア
    試走会完走 o-- 試走会向けコース作成
      試走会向けコース作成 o-- コース仕様把握
    試走会完走 o-- ログ機能_問題解析
  地区大会完走 o-- ロバスト性向上
    ロバスト性向上 o-- バッテリー対策
    ロバスト性向上 o-- 個体差調整
@enduml
